### ISSUE TITLE
crispy doom doesnt run

### ISSUE THREAD

**Issue by skullphantom241** [jmcerrejon/PiKISS#16]
it says error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: no such file or directory

**Comment by jmcerrejon** [comment]
Please make sure:

* You are using Raspberry Pi OS/Twister OS 32 bits.

* Good internet connection.

That's because something goes wrong when you run the script. This file _libSDL2_mixer-2.0.so.0_ is installed with the library _libsdl2-mixer-2.0-0_, installed by _PiKISS_ in the process. 

So try to run the script again (I've refactored some stuff) and send me some words about you success. 😉

**Comment by skullphantom241** [comment]
thanks so much
