### ISSUE TITLE
Autostart/Autoboot

### ISSUE THREAD

**Issue by actraiser30** [jmcerrejon/PiKISS#47]
Hello,i want to install a game for example Dune2
and then make it everytime the OS boots to autostart/autoboot the game automatically
is there such an option in your script?
if not can you add such an option to work with any of your games/servers etc ??

Also in the DuneLegacy game the mouse pointer is not visible,tried many different mouse`s but no luck
im using the latest raspbian buster image on a raspberry pi 3
can you fix that?

thanks

**Comment by jmcerrejon** [comment]
About autostart/autoboot an app on Debian, you have a dozen tutorials about that on the internet. It's not difficult.

I've installed DuneLegacy in the latest RPi OS 32 bits, and it's working here with a USB mouse.

![dunelegacy](https://user-images.githubusercontent.com/1942431/98541000-0d13c800-228f-11eb-9e0b-782b8cd6a54d.png)

**Comment by actraiser30** [comment]
i tried the game in raspbian lite probably you tried it in the desktop image is that correct ?
if yes is there a way to work in the non desktop image?

also the starcraft is not shown in the games menu only i can see the expansion and diablo1 is not showing also only diablo 2 is there

**Comment by jmcerrejon** [comment]
I always use Raspberry Pi OS 32 bits from here [here (direct link)](https://downloads.raspberrypi.org/raspios_armhf_latest) | [release notes](http://downloads.raspberrypi.org/raspios_armhf/release_notes.txt).

Maybe the issue is you don't have a desktop, try asking on Dune Legacy port [here](https://github.com/henricj/dunelegacy/issues).

Scripts are working here and I can see all the games. Try on the _Raspberry Pi OS_ I provided before and tell me if all issues are gone. That's the best advice I can give you now 🤷‍♂️ .

I'll add a note on README saying PiKISS is not compatible with Raspbian Lite.
