### ISSUE TITLE
Cant run ZOOM. AGAIN. Cant install box 86.

### ISSUE THREAD

**Issue by curyjorge98** [jmcerrejon/PiKISS#70]
Still in troubles. Now installing it through Emulators > Box86.

Im trying to run Zoom on my Raspberry PI OS (updated/upgraded).

My Username is not "pi" and I get this error on installing script for Box86:

Installing Box86...

Downloading...

box86.tar.gz        100%[===================>]  22,70M  1,44MB/s    em 18s     

Extracting...
[sudo] senha para vieira: 
/bin/sh: 1: cd: can't cd to /home/pi/box86/build
make[2]: *** [CMakeFiles/WRAPPERS.dir/build.make:287: CMakeFiles/WRAPPERS.dir/depend] Error 2
make[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/WRAPPERS.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Box86 has been installed.

Press [Enter] to go back to the menu...

Thanks,

Happy New Year.

Im trying to run Zoom on my Raspberry PI OS (updated/upgraded).

My Username is not "pi" and I get this error on installing script for Box86:

Extracting...
[sudo] senha para vieira:
/bin/sh: 1: cd: can't cd to /home/pi/box86/build
make[2]: *** [CMakeFiles/WRAPPERS.dir/build.make:287: CMakeFiles/WRAPPERS.dir/depend] Error 2
make[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/WRAPPERS.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Box86 has been installed.

Downloading...

zoom_i686.tar.xz 100%[===================>] 37,95M 1,76MB/s em 34s

Extracting...

Making a cool script called zoom-rpi.sh...

Generating icon...

Done!. Type /home/vieira/apps/zoom/zoom-rpi.sh or Go to Menu > Internet > Zoom.

Press [ENTER] to run...

Box86 missing, please install

Press [Enter] to go back to the menu...

Thanks,

Happy New Year.

@jmcerrejon jmcerrejon self-assigned this 2 days ago
@jmcerrejon jmcerrejon added the bug label 2 days ago
@jmcerrejon
 
Owner
jmcerrejon commented 2 days ago
Weird. It should be working because I always use $HOME (it should be /home/vieira). If box86 is the problem, you can install it through Emulators > Box86.

I close the issue but open this again if you get another issue.

**Comment by jmcerrejon** [comment]
I've added a new user on my RPi OS 32 bits, then added it to sudoers group with the command `sudo adduser vieira sudo`. Run the script again or you can manually copy the file if you have ~/box86 with  `sudo cp ~/box86/box86 /usr/local/bin/`.

I can't fix any other issues related to this or help you right now, so I have to close the issue, because is working with pi user, and that's the basic stage of almost all RPi users. You can try as alternative [Pi-apps ](https://github.com/Botspot/pi-apps). Apologies and good luck 😄
